//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Carts = new HashSet<Cart>();
            this.OrderProducts = new HashSet<OrderProduct>();
        }
        [Key]
        public int IdAccount { get; set; }

        [EmailAddress(ErrorMessage = "Please enter a valid email")]
        [Required(ErrorMessage = "Email not empty")]
        [RegularExpression("^[a-z0-9_\\+-]+(\\.[a-z0-9_\\+-]+)*@[a-z0-9-]+(\\.[a-z0-9]+)*\\.([a-z]{2,4})$", ErrorMessage = "Invalid email format.")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Phone not empty")]

        public string PhoneNumber { get; set; }
        [Required(ErrorMessage = "Name not empty")]
        public string NameAccount { get; set; }
        public string City { get; set; }
        public string Zip_Code { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter a valid password")]
        [DataType(DataType.Password)]
        [StringLength(20, ErrorMessage = "Password must 6 to 20 letter", MinimumLength = 6)]
        public string Password_User { get; set; }
        [Compare(otherProperty: "Password_User", ErrorMessage = " Confirm password does not match")]
        public string ConfirmPass { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProducts { get; set; }
    }
}