//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Category
    {
        [Key]
        public int IdCate { get; set; }
        [ForeignKey("IdPro")]
        public Nullable<int> IdPro { get; set; }
        public string NameCate { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
